### ISSUE TITLE
[TRACKER] V2 public release: documentation improvements

### ISSUE THREAD

**Issue by and3rson** [and3rson/lilka#97]
* [x] Інфо про нюанси спільної шини SPI для дисплея і SD-карти
* [x] Інфо про компромісні рішення в дизайні Лілки V2
* [x] #23
* [x] Ієрархія фреймворків/бібліотек: lilka -> arduino -> idf
* [x] #107
